#

IMAGE_WIDTH = 1920
IMAGE_HEIGHT = 1080
IMAGE_PIXELS = IMAGE_WIDTH * IMAGE_HEIGHT
IMAGE_BITS = IMAGE_PIXELS * 24

RS_SYMBOL = 8
RS_CODEWORD = 255 * RS_SYMBOL
RS_MESSAGE = 239 * RS_SYMBOL
RS_PARITY = RS_CODEWORD - RS_MESSAGE
RS_CAPABILITY = RS_PARITY // RS_SYMBOL // 2

HAMMING_CODEWORD = 128
HAMMING_MESSAGE = 120
HAMMING_PARITY = HAMMING_CODEWORD - HAMMING_MESSAGE

GE2_GOOD_TO_BAD = 0.001
GE2_BAD_TO_GOOD = 0.5